language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - python setup.py install --quiet
    - pip install --quiet pytest-cov

script:
    - nosetests --with-coverage --cover-package=pep8radius

after_success:
    - pip install --quiet coveralls
    - coveralls
